spring:
  application:
    name: contas-receber
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cobranca?useTimezone=true&serverTimezone=UTC
    username: cobrancaUser
    password: cobranca
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
      show-sql: false
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Disable caching for development
    mode: HTML
    encoding: UTF-8
  messages:
    basename: templates/i18n/messages_pt_BR
    encoding: UTF-8

logging:
  level: # Log Level: ERROR, WARN, INFO, DEBUG, or TRACE
    root: WARN
    br.com.zuco: DEBUG
