spring:
  application:
    name: contas-receber
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cobranca?useTimezone=true&serverTimezone=UTC
    username: cobrancaUser
    password: cobranca
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
      show-sql: false
      open-in-view: false
  logging:
    level:
      root: INFO
      br.com.zuco: DEBUG
