spring:
  application:
    name: contas-receber
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
        show-sql: false
        open-in-view: false
  logging:
    level:
      root: INFO
      br.com.zuco: DEBUG
